# .github/workflows/validate.yml
# GitHub Actions configuration file for validating the BibLaTeX files
# See ?? for details

name: validate

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  validate:
    name: Validate the BibLaTeX files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup TeX Live
        uses: teatimeguest/setup-texlive-action@v3
        with:
          packages: biber

      - name: Run the validations
        run: |
          biber --dieondatamodel --no-default-datamodel --validate-config --validate-datamodel --output-file=ragonneau_bibertool.bib --tool strings.bib ragonneau.bib
          biber --dieondatamodel --no-default-datamodel --validate-config --validate-datamodel --output-file=ragonneau-long_bibertool.bib --tool strings-long.bib ragonneau.bib
          biber --dieondatamodel --no-default-datamodel --validate-config --validate-datamodel --output-file=optim_bibertool.bib --tool strings.bib optim.bib
          biber --dieondatamodel --no-default-datamodel --validate-config --validate-datamodel --output-file=optim-long_bibertool.bib --tool strings-long.bib optim.bib

      - name: Store artifacts
        uses: actions/upload-artifact@v3
        with:
          path: "*_bibertool.bib"
          if-no-files-found: error
